name = "stake-multi-proxy"
main = "worker.js"
compatibility_date = "2024-01-01"

# After running: wrangler kv:namespace create ODDS_CACHE
# paste the id below
[[kv_namespaces]]
binding = "ODDS_CACHE"
id = "e244bca297b14e1a86c258cc390923f5"
